### ISSUE TITLE
generate-springmvc-endpoints failed

### ISSUE THREAD

**Issue by hamza-busuri** [phoenixnap/springmvc-raml-plugin-sample#3]
When I follow the steps to run the app, I get the following build failure error.

Execution generate-springmvc-controllers of goal com.phoenixnap.oss:springmvc-raml-plugin:0.8.6:generate-springmvc-endpoints failed: A required class was missing while executing com.phoenixnap.oss:springmvc-raml-plugin:0.8.6:generate-springmvc-endpoints: javax/xml/bind/SchemaOutputResolver

Does anyone know how to resolve this?

**Comment by stojsavljevic** [comment]
Discussion moved here: https://github.com/phoenixnap/springmvc-raml-plugin/issues/306#issuecomment-574267823
